---

services:
  postgresql:
    image: postgres:17-alpine
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=java-fastfile

volumes:
  postgres-data: